export default {
  'Pol': require("../images/categories/political_icon.png"),
  'Env': require("../images/categories/science_icon.png"),
  'Lif': require("../images/categories/lifestyle_icon.png"),
  'Hum': require("../images/categories/news_icon.png"),
  'Oth': require("../images/categories/other_icon.png"),
  'All': require("../images/categories/all_icon.png"),
  'Jus': require("../images/categories/technology_icon.png"),
  'Spo': require("../images/categories/sports_icon.png"),
  'Ent': require("../images/categories/arts_icon.png"),
  'Tec': require("../images/categories/business_icon.png"),

  'Pol_browse': require("../images/browseCategories/political_icon.png"),
  'Env_browse': require("../images/browseCategories/science_icon.png"),
  'Lif_browse': require("../images/browseCategories/lifestyle_icon.png"),
  'Hum_browse': require("../images/browseCategories/news_icon.png"),
  'Oth_browse': require("../images/browseCategories/other_icon.png"),
  'All_browse': require("../images/browseCategories/all_icon.png"),
  'Jus_browse': require("../images/browseCategories/technology_icon.png"),
  'Spo_browse': require("../images/browseCategories/sports_icon.png"),
  'Ent_browse': require("../images/browseCategories/arts_icon.png"),
  'Tec_browse': require("../images/browseCategories/business_icon.png"),

  'Trending': require("../images/categories/trending_icon.png"),
  'Ending Soon': require("../images/categories/endingsoon_icon.png"),
  'Latest': require("../images/categories/latestPolls_icon.png"),
  'Featured Polls': require("../images/categories/starPolls_icon.png"),
  'My Votes': require("../images/categories/myVotes_icon.png"),
  'My Polls': require("../images/categories/myPolls_icon.png"),
  'Local': require("../images/categories/local_icon.png"),
  'National': require("../images/categories/national_icon.png"),
  'Friends Voted On...': require("../images/categories/social_icon.png"),
  'Social': require("../images/categories/social_icon.png"),
  'Political & Human Rights': require("../images/categories/political_icon.png"),
  'News & Current Events': require("../images/categories/news_icon.png"),
  'Lifestyle & Health': require("../images/categories/lifestyle_icon.png"),
  'Sports, Hobbies & Games': require("../images/categories/sports_icon.png"),
  'Business & Finance': require("../images/categories/business_icon.png"),
  'Science & Nature': require("../images/categories/science_icon.png"),
  'Technology & Gadgets': require("../images/categories/technology_icon.png"),
  'Arts & Entertainment': require("../images/categories/arts_icon.png"),
  'Everything Else': require("../images/categories/everythingElse_icon.png"),
  'Random': require("../images/categories/random_icon.png"),
  'All Categories': require("../images/categories/all_icon.png"),
  'All Categories': require("../images/categories/all_icon.png"),
}
